### ISSUE TITLE
error in deploy

### ISSUE THREAD

**Issue by yeganx** [abouchama/karaf-camel-rest-ose#1]
hi 
 mvn clean install is successful but 
when i want deploy the code error occured 
[INFO] --- karaf-maven-plugin:4.0.2.redhat-621079:archive (karaf-archive) @ karaf-camel-rest-ose ---
[INFO] 
[INFO] --- docker-maven-plugin:0.13.6:build (default-cli) @ karaf-camel-rest-ose ---
[ERROR] DOCKER> sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.782 s
[INFO] Finished at: 2017-01-12T15:42:32+03:30
[INFO] Final Memory: 49M/708M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.6:build (default-cli) on project karaf-camel-rest-ose: Unable to check image [jboss-fuse-6/fis-karaf-openshift:1.0] -> [Help 1]
my docker ps is running and docker_host and cert_path is imported

**Comment by abouchama** [comment]
Hi @yeganx ,

From your ERROR, it seems you are not connected to Openshift.

please before running deploy; run the following commands:

```
eval "$(vagrant service-manager env docker)" --> This will allow to set all variables related to docker.
oc login https://10.1.2.2:8443 -u admin -p admin --> Connect to OSE
```

Please give a try and keep me informed about the result.

**Comment by yeganx** [comment]
thank you
i was connected to openshift 
in other try . I get this error
[INFO] 
[INFO] --- docker-maven-plugin:0.13.6:push (default-cli) @ karaf-camel-rest-ose ---
[INFO] DOCKER> ... The push refers to a repository [registry.access.redhat.com/fabric8/quickstart-karaf-camellog]
[INFO] DOCKER> ... 67c65fc75af3 Preparing
[INFO] DOCKER> ... 146ad8ea2752 Preparing
[INFO] DOCKER> ... 51d480ff0427 Preparing
[INFO] DOCKER> ... 2f2c71ba7d1a Preparing
[INFO] DOCKER> ... a2de66622680 Preparing
[INFO] DOCKER> ... 22426f366c51 Preparing
[INFO] DOCKER> ... 94b2db70f747 Preparing
[INFO] DOCKER> ... 22426f366c51 Waiting
[INFO] DOCKER> ... 94b2db70f747 Waiting
[INFO] DOCKER> ... 94b2db70f747 Waiting
[INFO] DOCKER> ... 22426f366c51 Waiting
[ERROR] DOCKER> Error parsing HTTP response: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>405 Method Not Allowed</title>\n<h1>Method Not Allowed</h1>\n<p>The method POST is not allowed for the requested URL.</p>\n" 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:08 min
[INFO] Finished at: 2017-01-14T10:36:43+03:30
[INFO] Final Memory: 50M/420M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.6:push (default-cli) on project karaf-camel-rest-ose: Unable to push 'fabric8/quickstart-karaf-camellog:1.0.0-SNAPSHOT' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by yeganx** [comment]
thank you
i was connected to openshift 
in other try . I get this error
[INFO] 
[INFO] --- docker-maven-plugin:0.13.6:push (default-cli) @ karaf-camel-rest-ose ---
[INFO] DOCKER> ... The push refers to a repository [registry.access.redhat.com/fabric8/quickstart-karaf-camellog]
[INFO] DOCKER> ... 67c65fc75af3 Preparing
[INFO] DOCKER> ... 146ad8ea2752 Preparing
[INFO] DOCKER> ... 51d480ff0427 Preparing
[INFO] DOCKER> ... 2f2c71ba7d1a Preparing
[INFO] DOCKER> ... a2de66622680 Preparing
[INFO] DOCKER> ... 22426f366c51 Preparing
[INFO] DOCKER> ... 94b2db70f747 Preparing
[INFO] DOCKER> ... 22426f366c51 Waiting
[INFO] DOCKER> ... 94b2db70f747 Waiting
[INFO] DOCKER> ... 94b2db70f747 Waiting
[INFO] DOCKER> ... 22426f366c51 Waiting
[ERROR] DOCKER> Error parsing HTTP response: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>405 Method Not Allowed</title>\n<h1>Method Not Allowed</h1>\n<p>The method POST is not allowed for the requested URL.</p>\n" 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:08 min
[INFO] Finished at: 2017-01-14T10:36:43+03:30
[INFO] Final Memory: 50M/420M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.6:push (default-cli) on project karaf-camel-rest-ose: Unable to push 'fabric8/quickstart-karaf-camellog:1.0.0-SNAPSHOT' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by yeganx** [comment]
I've deploy it in S2I method , but no service and route is created ! how can I handle it
in addition S2I method is too slow , how can I deploy it with fabric method without error

**Comment by yeganx** [comment]
ooh mvn -Pf8-local-deploy!!! solved my problem 
now i have problem in changig the route . I want send msg to activemq on my openshift 3 not to direct .
can you help me to solve it

**Comment by yeganx** [comment]
I add this dependency to pom file 
```
 <dependency>
      <groupId>org.apache.activemq</groupId>
      <artifactId>activemq-client</artifactId>
      <version>5.14.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.activemq</groupId>
      <artifactId>activemq-camel</artifactId>
      <version>5.14.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.activemq</groupId>
      <artifactId>activemq-pool</artifactId>
      <version>5.14.0</version>
    </dependency>

```

and add to camel-rest.xml 
```
<bean class="org.apache.activemq.camel.component.ActiveMQComponent" id="activemq">
        <property name="brokerURL" value="tcp://${env+service:ACTIVEMQ_SERVICE_NAME}"/>
        <property name="userName" value="${env:ACTIVEMQ_USERNAME}"/>
        <property name="password" value="${env:ACTIVEMQ_PASSWORD}"/>
    </bean>
```
and change it to 
```
<rest path="FIS">
            <get uri="/{name}">
                <to uri="activemq:order"/>
            </get>
        </rest
```

get these errors 
[INFO] Loading profiles
[INFO] Downloading libraries
[INFO] Loading repositories
[INFO] Resolving features
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.892 s
[INFO] Finished at: 2017-01-14T18:18:13+03:30
[INFO] Final Memory: 51M/726M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.0.2.redhat-621079:assembly (karaf-assembly) on project karaf-camel-rest-ose: Unable to build assembly: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=org.apache.activemq.activemq-client; type=osgi.bundle; version="[5.14.0,5.14.0]"; resolution:=mandatory [caused by: Unable to resolve org.apache.activemq.activemq-client/5.14.0: missing requirement [org.apache.activemq.activemq-client/5.14.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=javax.jms)(version>=1.1.0)(!(version>=2.0.0)))"] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
